name: geoh2
channels:
  - defaults

dependencies:
  - python
  - atlite
  - cdsapi
  - geopandas
  - geopy
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - PySimpleGUI
  - shapely
  - xlsxwriter

