name: geoh2
channels:
  - conda-forge
  - nodefaults

dependencies:
  - atlite=0.2.10
  - cartopy
  - gdal=3
  - geopandas
  - geopy
  - matplotlib
  - numpy
  - openpyxl
  - pandas=2.1.4
  - pip
  - pypsa=0.26.0
  - python
  - shapely=1.8.4
  - xarray 
