name: geoh2
channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - atlite
  - cartopy
  - gdal
  - geopy
  - geopandas
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - pypsa
  - rasterio!=1.2.10
  - shapely=1.8.4
  - xlsxwriter

  - pip:
    - cdsapi
    - geopy
    - PySimpleGUI
