name: geoh2
channels:
  - defaults
  - conda-forge

dependencies:
  - python
  - atlite
  - geopandas
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pip
  - shapely
  - xlsxwriter

  - pip:
    - cdsapi
    - geopy
    - PySimpleGUI